nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false
        skip_same_as_origin: true
    paths:
        '^/':
            allow_headers: [ 'Content-Type', 'Authorization']
            allow_methods: [ 'GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE' ]
            allow_origin: [ '*' ]
            forced_allow_origin_value: false
            max_age: 3600