api_login_check:
    path: /api/login_check
post:
    resource:
        path: ../src/Post/Controller/
        namespace: App\Post\Controller
    type: attribute

user:
    resource:
        path: ../src/User/Controller/
        namespace: App\User\Controller
    type: attribute


